---
title: "Czas"
output: pdf_document
date: "2023-08-17"
header-includes:
      - \usepackage{pdflscape}
---

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(dplyr)
library(ggplot2)
library(rstudioapi)
library(knitr)
library(kableExtra)

# setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```


```{r, echo=FALSE}
data <- read.csv("czas.csv")
data$czas <- substring(data$czas, 8, length(data$czas))
colnames(data) <- c("czas", "Wrocław - Biały", "Wrocław - Kraków", "Kraków - Biały")
data |>
  dplyr::mutate(`Wrocław - Biały` = paste(`Wrocław - Biały`%/%60, "h", `Wrocław - Biały` %% 60, "min")) |> 
  dplyr::mutate(`Wrocław - Kraków` = paste(`Wrocław - Kraków`%/%60, "h", `Wrocław - Kraków` %% 60, "min")) |> 
  dplyr::mutate(`Kraków - Biały` = paste(`Kraków - Biały`%/%60, "h", `Kraków - Biały` %% 60, "min")) |> 
  knitr::kable(
    format = "latex",
    align = "l",
    booktabs = TRUE,
    longtable = TRUE,
    linesep = "",
    ) %>%
  kableExtra::kable_styling(
      position = "center",
      latex_options = c("striped", "repeat_header"),
      stripe_color = "gray!15"
    )
```


```{r, echo=FALSE, results=FALSE}
fastest <- data |> 
  dplyr::filter(`Wrocław - Biały` == min(`Wrocław - Biały`)) |> 
  dplyr::mutate(`Wrocław - Biały` = paste(`Wrocław - Biały`%/%60, "h", `Wrocław - Biały` %% 60, "min")) |> 
  dplyr::mutate(`Wrocław - Kraków` = paste(`Wrocław - Kraków`%/%60, "h", `Wrocław - Kraków` %% 60, "min")) |> 
  dplyr::mutate(`Kraków - Biały` = paste(`Kraków - Biały`%/%60, "h", `Kraków - Biały` %% 60, "min"))
slowest <- data |> 
  dplyr::filter(`Wrocław - Biały` == max(`Wrocław - Biały`)) |> 
  dplyr::mutate(`Wrocław - Biały` = paste(`Wrocław - Biały`%/%60, "h", `Wrocław - Biały` %% 60, "min")) |> 
  dplyr::mutate(`Wrocław - Kraków` = paste(`Wrocław - Kraków`%/%60, "h", `Wrocław - Kraków` %% 60, "min")) |> 
  dplyr::mutate(`Kraków - Biały` = paste(`Kraków - Biały`%/%60, "h", `Kraków - Biały` %% 60, "min"))
```

Najszybciej się dojedzie jak się wyjedzie o **`r fastest$czas`**, wtedy planowo jest **`r fastest$"Wrocław - Biały"[1]`**, a najwolniej jak się wyjedzie o **`r slowest$czas`**, wtedy planowo jest **`r slowest$"Wrocław - Biały"[1]`**.

\newpage
```{r, echo=FALSE, out.extra='angle=90', out.width="150%", out.height="150%"}
ggplot(data=data, aes(x = seq(1,nrow(data)))) + 
  geom_point(aes(y=`Wrocław - Biały`)) +
  geom_line(aes(y=`Wrocław - Biały`)) +
  labs(title="Czas w minutach Wrocław - Biały", y="Minuty", x="Godzina odjazdu") +
  theme(axis.text.x = element_text(angle = 90, size=rel(1)),
        axis.text.y = element_text(size=rel(1)),
        plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(breaks = seq(1,nrow(data)),
                     labels = as.character(data$czas))
```


\newpage
```{r, echo=FALSE, out.extra='angle=90', out.width="150%", out.height="150%"}
ggplot(data=data, aes(x = seq(1,nrow(data)))) + 
  geom_point(aes(y=`Wrocław - Kraków`)) +
  geom_line(aes(y=`Wrocław - Kraków`)) +
  labs(title="Czas w minutach Wrocław - Kraków", y="Minuty", x="Godzina odjazdu") +
  theme(axis.text.x = element_text(angle = 90, size=rel(1)),
        axis.text.y = element_text(size=rel(1)),
        plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(breaks = seq(1,nrow(data)),
                     labels = as.character(data$czas))
```
\newpage
```{r, echo=FALSE, out.extra='angle=90', out.width="150%", out.height="150%"}
ggplot(data=data, aes(x = seq(1,nrow(data)))) + 
  geom_point(aes(y=`Kraków - Biały`)) +
  geom_line(aes(y=`Kraków - Biały`)) +
  labs(title="Czas w minutach Kraków - Biały", y="Minuty", x="Godzina odjazdu") +
  theme(axis.text.x = element_text(angle = 90, size=rel(1)),
        axis.text.y = element_text(size=rel(1)),
        plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(breaks = seq(1,nrow(data)),
                     labels = as.character(data$czas))
```








