---
title: "Untitled"
output: html_document
date: "2023-08-21"
---

```{r, warning=F, message=F}
library(dplyr)
library(tibble)
library(ggplot2)
```


```{r}
dataframe <- read.delim("czas20.csv")

dataframe <- sapply(1:nrow(dataframe), function(i){
    dataframe[i, 1] <- gsub(",,", "", dataframe[i, 1])
  })
date <- sapply(2:length(dataframe), function(i){
  dataframe[i] |> substring(1, 12)
})
value <- sapply(2:length(dataframe), function(i){
  dataframe[i] |> substring(14, 16)
})

dataframe <- tibble::tibble(`Bielany - pwr` = date,
                            `czas` = value) |> 
  dplyr::mutate(`czas` = as.numeric(czas)) |> 
  dplyr::mutate(`czas` = czas)

dataframe
```

```{r}
dataframe2 <- read.csv("czas9.csv")
dataframe2
```

```{r}
df3 <- read.csv("czas18.csv")
df3
```

```{r}
ggplot(data=df3, aes(x = seq(1, nrow(df3)))) + 
  geom_point(aes(y=`Bielany...pwr`)) +
  geom_line(aes(y=`Bielany...pwr`)) +
  labs(title="Czas w minutach Bielany - pwr", y="czas", x="Bielany - pwr") +
  theme(axis.text.x = element_text(angle = 90, size=rel(1)),
        axis.text.y = element_text(size=rel(1)),
        plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(breaks = seq(1,nrow(df3)),
                     labels = as.character(df3$czas))
```



